accounts/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'account'

urlpatterns = [
    path('signup/',SignUpView.as_view(), name='signup'),
]

blog/urls.py
from pickletools import UP_TO_NEWLINE
from unicodedata import name
from django.urls import path
from django.views import *

from blog.views import BlogListView, DetailPost, CreatePost, UpdatePost, DeletePost

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('post/<int:pk>', DetailPost.as_view(), name='detail-post'),
    path('new/', CreatePost.as_view(), name='new-post'),
    path('update/<int:pk>', UpdatePost.as_view(), name='update-post'),
    path('delete/<int:pk>', DeletePost.as_view(), name='delete-post'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
     path('app/', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

app_name = 'page'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class CustomeUser(AbstractUser):
    age = models.PositiveBigIntegerField(null=True, blank=True)
    about = models.TextField(default='', blank=True)

blog/models.py
from django.db import models

from django.contrib.auth import get_user_model
from django.urls import reverse


# Create your models here.
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آی پی')

    def __str__(self):
        return self.ip_address


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('accounts.CustomeUser', on_delete=models.CASCADE)
    body = models.TextField()

    hits = models.ManyToManyField(IPAddress, blank=True,related_name='hits', verbose_name='بازدیدها')
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail-post', args=[str(self.id)])

class Comment(models.Model):
    comment = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.comment
    
    def get_absolute_url(self):
        return reverse('blog:detail-post', args=[str(self.id)])


class MyModel(models.Model):
    title = models.CharField(max_length=200)
    phone = models.IntegerField(null=True)
    
    def __str__(self):
        return self.title
    

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomeUser

class CustomeUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomeUser
        # fields = UserCreationForm.Meta.fields + ('age', 'is_staff', 'is_superuser')
        fields = ('username', 'email', 'age', 'is_superuser')


class CustomeUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomeUser
        fields = UserCreationForm.Meta.fields

blog/forms.py
from socket import fromshare
from django import forms

from .models import Comment

class formComment(forms.ModelForm):
    
    class Meta:
        medel = Comment

        fields = ['comment', 'post']

accounts/views.py
import imp
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomeUserCreationForm
# Create your views here.

class SignUpView(generic.CreateView):
    form_class = CustomeUserCreationForm #UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blog/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post, Comment
# Create your views here.

# class BlogListView(ListView):
#     model = Post
#     template_name = 'blog/home.html'
#     context_object_name = 'all_posts'

class BlogListView(ListView):
    model = Post
    template_name = 'blog/home.html'

class DetailPost(DetailView):
    model =Post
    template_name = 'blog/post.html'
    def get_object(self):
        pk = self.kwargs.get('pk')
        object = get_object_or_404(Post.objects.all(), id = pk)
        ip_address = self.request.user.ip_address
        if ip_address not in object.hits.all():
            object.hits.add(ip_address)
        return object


    # def post(self, request, *args, **kwargs):
    #     new_comment = Comment(comment= request.Post.get('comment'),
    #         post = request.Post.get('post'),
    #         author = self.request.user
    #     )
    










class CreatePost(LoginRequiredMixin ,CreateView):
    model = Post
    template_name = 'blog/create.html'
    fields = ['title',  'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePost(LoginRequiredMixin, UserPassesTestMixin ,UpdateView):
    model = Post
    template_name = 'blog/update.html'
    fields = ['title', 'body',]
    # success_url = reverse_lazy('blog:home')
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class DeletePost(LoginRequiredMixin, UserPassesTestMixin ,DeleteView):
    model = Post
    template_name = 'blog/delete.html'
    success_url =reverse_lazy('blog:home')
    
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        site |
        {% endblock title %}
    </title>

    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Newspaper</a>
        <a class="navbar-brand btn btn-primary" href="{% url 'blog:new-post' %}">New</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            Log Out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">
                    Log In</a>
                <a href="{% url 'account:signup' %}" class="btn btn-primary ml-2">
                    Sign up</a>
            </form>
            {% endif %}
        </div>
    </nav>
    <main>
        <div class="container py-4">
            {% block main %}
            {% endblock main %}
        </div>
    </main>
    
    <!-- js -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/blog/create.html
{% extends 'blog/base.html' %}


{% block main %}
<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="save">
</form>
{% endblock %}

templates/blog/delete.html
{% extends 'blog/base.html' %}


{% block main %}
<form action="" method="post">
{% csrf_token %}
{{post.title}}
<input type="submit" value="save">
</form>
{% endblock %}

templates/blog/home.html
{% extends 'blog/base.html' %}

{% block main %}

{% for p in object_list %}
    <div>
        <h2>{{p.title}}</h2>
        <p>user: {{p.author}}</p>
        <p>{{p.body}}</p>
        <br>
        <a href="{% url 'blog:detail-post' p.pk %}">show</a>
    </div>
    <hr>

{%endfor%}
{% endblock main %}

templates/blog/post.html
{% extends 'blog/base.html' %}

{% block main %}

<div>
    <h2>{{object.title}}</h2>
    <p>user: {{object.author}}</p>
    <p>{{object.body}}</p>
    <p>{{object.hits.count}}</p>
</div>

<a href="{% url 'blog:update-post' post.pk %}">Edit</a>
<a href="{% url 'blog:delete-post' post.pk %}">Delete</a>
<hr>

<hr>
{% for cm in object.comments.all %}
    <div>
        <h4>{{cm.author}}</h4>
        <p>{{cm.comment}}</p>
    </div>
    <hr>
{% endfor %}
{% endblock %}

templates/blog/update.html
{% extends 'blog/base.html' %}


{% block main %}
<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="save">
</form>
{% endblock %}

templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css" integrity="sha512-T584yQ/tdRR5QwOpfvDfVQUidzfgc2339Lc8uBDtcp/wYu80d7jwBgAxbyMh0a9YM9F8N3tdErpFI8iaGx6x5g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    {% block main %}

    {% endblock%}
    <!-- js -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.min.js" integrity="sha512-UR25UO94eTnCVwjbXozyeVd6ZqpaAE9naiEUBK/A+QDbfSTQFhPGj5lOR6d8tsgbBk84Ggb5A3EkjsOgPRPcKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

templates/pages/home.htm
{% extends 'base.html'%}

{% block main %}

{% endblock %}